name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: npm run cy:run:chrome & npm run cy:run:firefox
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
          record: true
        env:
          # for recording test results and videos to Cypress Dashboard
          CYPRESS_RECORD_KEY: d796c79f-ddee-4af4-af5b-08974fbd8a3c
