name: Cypress Tests

on: [push]

jobs:
 install : 
    container: cypress/browsers:latest
    needs: install
      name : cypress-run
      runs-on: ubuntu-latest
      strategy:
        # when one test fails, DO NOT cancel the other
        # containers, because this will kill Cypress processes
        # leaving the Dashboard hanging ...
        # https://github.com/cypress-io/github-action/issues/48
        fail-fast: false
        matrix:
          # run 3 copies of the current job in parallel
          containers: [1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress Parallel Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run start
          
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          # for recording test results and videos to Cypress Dashboard
          CYPRESS_RECORD_KEY: d796c79f-ddee-4af4-af5b-08974fbd8a3c
