name: Cypress Tests

on: [push]

jobs:
install:
  # ...
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build
      # and run all Cypress tests
      - name: npm run cy:run:chrome & npm run cy:run:firefox
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
          record: true
          build: yarn build
          install: false
          start: yarn start:ci
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          # for recording test results and videos to Cypress Dashboard
          CYPRESS_RECORD_KEY: d796c79f-ddee-4af4-af5b-08974fbd8a3c
